(function() {var implementors = {};
implementors["protobuf"] = [];
implementors["raft"] = [{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.Entry.html\" title=\"struct raft::eraftpb::Entry\">Entry</a>",synthetic:false,types:["raft::eraftpb::Entry"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.SnapshotMetadata.html\" title=\"struct raft::eraftpb::SnapshotMetadata\">SnapshotMetadata</a>",synthetic:false,types:["raft::eraftpb::SnapshotMetadata"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.Snapshot.html\" title=\"struct raft::eraftpb::Snapshot\">Snapshot</a>",synthetic:false,types:["raft::eraftpb::Snapshot"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.Message.html\" title=\"struct raft::eraftpb::Message\">Message</a>",synthetic:false,types:["raft::eraftpb::Message"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.HardState.html\" title=\"struct raft::eraftpb::HardState\">HardState</a>",synthetic:false,types:["raft::eraftpb::HardState"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.ConfState.html\" title=\"struct raft::eraftpb::ConfState\">ConfState</a>",synthetic:false,types:["raft::eraftpb::ConfState"]},{text:"impl <a class=\"trait\" href=\"protobuf/clear/trait.Clear.html\" title=\"trait protobuf::clear::Clear\">Clear</a> for <a class=\"struct\" href=\"raft/eraftpb/struct.ConfChange.html\" title=\"struct raft::eraftpb::ConfChange\">ConfChange</a>",synthetic:false,types:["raft::eraftpb::ConfChange"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
